name: Manually Triggered NPM Workflow
on:
  workflow_dispatch:
  
jobs:
  NodeBuildAndTest:
    # Importing a reusable workflow from another repository and branch
    uses: HexaWorkflowTemplates/CalledWorkflows/.github/workflows/nodejs-build-unittest.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
  SonarQubeAnalysis:
    name: SonarCloud Scan
    uses: HexaWorkflowTemplates/CalledWorkflows/.github/workflows/sonarscan.yml@main
