name: Manually Triggered NPM Workflow
on:
  workflow_dispatch:
jobs:
  call-codeQL-analysis:
    name: CodeQL analysis
    uses: HexaWorkflowTemplates/CalledWorkflows/.github/workflows/codeql-analysis.yml@main
