name: Manually Triggered NPM Workflow
on:
  workflow_dispatch:
jobs:
  call-codeQL-analysis:
    name: CodeQL analysis
    uses: HexaWorkflowTemplates/CalledWorkflows/.github/workflows/codeql-analysis.yml@main
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: HexaWorkflowTemplates/CalledWorkflows/.github/workflows/nodejs-build-unittest.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
