name: publish
env:
  CI: true
on:
  push:
    branches:
      - master
    tags:
      - "!*"
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          npm-registry:
            - registry: 'https://npm.pkg.github.com'
              scope: '@azu'
              token: '${{secrets.GITHUB_TOKEN}}'
      - name: install
        run: npm install
      - name: test
        run: npm test
      - name: npm-publish-with-git-tag
        uses: azu/action-npm-publish-with-git-tag@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
