name: publish
env:
  CI: true
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - name: install can-npm-publish and dependencies
        run: |
          npm install --global can-npm-publish
          npm install
      - name: test
        run: npm test
      - name: Publish
        run: |
          can-npm-publish --verbose && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
